language: node_js
node_js:
  - 13
services:
  - docker
install:
  - echo "nothing needs to be installed"
before_script:
  - echo "no tests"
script:
  - docker --version 
  - cd udagram-api-feed/
  - docker build -t quanlh0604/api-feed .
  - cd ..
  - cd udagram-api-user/
  - docker build -t quanlh0604/api-user .
  - cd ..
  - cd udagram-frontend/
  - docker build -t quanlh0604/frontend .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quanlh0604/api-feed
  - docker push quanlh0604/api-user
  - docker push quanlh0604/frontend