apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
       service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: quanlh0604/api-user:1.0.0
        name: backend-user
        imagePullPolicy: Always          
        resources:
          limits:
            memory: "2048Mi"
            cpu: "700m"           
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: special-config-user 
          - secretRef:
              name: mysecret-user    
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-user