apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
       service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: quanlh0604/reverseproxy:1.0.0
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    service: reverseproxy