apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
       service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: quanlh0604/api-feed:1.0.0
        name: backend-feed
        imagePullPolicy: Always          
        resources:
          limits:
            memory: "2048Mi"
            cpu: "700m"       
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: special-config
          - secretRef:
              name: mysecret    
#      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed